### ISSUE TITLE
last_indications_date не обновился после передачи показаний

### ISSUE THREAD

**Issue by andreypolyak** [alryaz/hass-lkcomu-interrao#18]
Добрый день, спасибо за компонент!

Недавно настроил автоматизацию, которая автоматически передает показания 16, 17, 18 числа каждого месяца несколько раз в день в Мосэнергосбыт. Каждый раз перед отправкой показаний проверяется дата в атрибуте last_indications_date сенсора sensor.mosenergosbyt_meter. Если дата соответствует текущему месяцу, то отправка не производится. Это сделано для того, чтобы гарантированно отправить показания за месяц, даже если система на стороне поставщика временно не работает.

Сегодня показания были успешно переданы (даже несколько раз). Скрин из ЛК Мосэнергосбыта:
<img width="942" alt="Screenshot 2021-11-16 at 13 19 19" src="https://user-images.githubusercontent.com/7446762/141967289-e1bd275a-069f-4e72-a4cf-0bc424fc8784.png">

Однако в сенсоре счётчика по-прежнему старая дата:
```YAML
attribution: Данные получены с my.mosenergosbyt.ru
meter_code: %вырезано%
account_code: %вырезано%
model: Меркурий 206
install_date: '2021-04-15'
submit_period_start: '2021-11-15'
submit_period_end: '2021-11-26'
submit_period_active: true
remaining_days: 10
last_indications_date: '2021-10-16'
zone_t1_name: пик (Т1)
zone_t1_last_indication: 885
zone_t1_today_indication: 964
zone_t1_period_indication: 964
zone_t2_name: ночь (Т2)
zone_t2_last_indication: 824
zone_t2_today_indication: 885
zone_t2_period_indication: 885
zone_t3_name: полупик (Т3)
zone_t3_last_indication: 1288
zone_t3_today_indication: 1404
zone_t3_period_indication: 1404
account_id: %вырезано%
friendly_name: Mosenergosbyt Meter
icon: mdi:counter
supported_features: 3
device_class: lkcomu_interrao_meter
```
Это проблема на стороне компонента или API поставщика? Можно ли что-то сделать с этим?
