### ISSUE TITLE
Проблема с недоступностью сайта Мосэнергосбыта в ночное время с вытекающими последствиями

### ISSUE THREAD

**Issue by booroondook-eng** [alryaz/hass-lkcomu-interrao#40]
С некоторых пор (года два уже, наверное) сайт mosenergosbyt.ru не работает в ночное время, а точнее - с 23:00 до 08:00.
Соответственно, если перезапуск Home Assistant по какой-либо причине пришелся на этот период времени, то данная интеграция не запускается, выдавая ошибку. Проблема устраняется принудительным перезапуском интеграции в период с 08:00 до 23:00 - то есть, во время доступности сайта Мосэнеросбыта. Однако, если не вспомнить про перезапуск интеграции, то она так и остается "висеть" с ошибкой.
Другими словами, перезапуск интеграции вызывает "вечную" ошибку, если этот перезапуск произошел ночью, и не вызывает ошибки, если перезапуск произошел днем. Если перезапусков не было, то даже в ночное время интеграция не выдает никаких ошибок.
Можно ли как-то решить этот вопрос в том плане, чтобы перезапуск интеграции (вручную ли, или же вместе с перезапуском ХА) не вызывал ошибки даже при недоступности сервера Мосэнергосбыта?

**Comment by staseek** [comment]
В качестве решения добавил автоматизацию, вроде работает 

```
- alias: Restart Inter RAO Personal Cabinet (Energosbyt) by time if it is unavaliable
  trigger:
  - platform: time
    at: "08:30"
  conditions:
  - condition: state
    entity_id: sensor.mes_XXX_account
    state: 'unavailable'
  action:
  - service: homeassistant.reload_config_entry
    target: {}
    data:
      entry_id: id_интеграции
```

Id интеграции можно найти в Developer Tools браузера, если вызвать руками перезагрузку интеграции

```POST http://192.168.4.88:8123/api/config/config_entries/entry/id_интеграции/reload```
